### PR TITLE
fixed some formatting, cleaned up

### PR DESCRIPTION
**Pull request by joelis10**
I haven't had much time recently to contribute much more or get Docker working locally, but here's my contribution.

### CODE REVIEW

**Review by Realitaetsverlust — APPROVED** [review]
Thanks for your contribution! Looks all good aswell. 

I'll merge them and update the site probably at the weekend.

**Comment by joelis10** [comment]
not sure if the site needs updating or if it's a GitHub issue but I don't think I can see my changes yet and it's been over a month

**Comment by Realitaetsverlust** [comment]
@joelis10 Hi, sorry about that massive delay. I was in hospital and just didn't find the time or energy to do anything in this project.

I just got home and have updated the site with your changes.

**Comment by joelis10** [comment]
I'm sorry to hear that but thank you for letting me know, hope all is well in regards to your health

**Pull request merged**
